package hexlet.code;

import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.time.LocalDateTime;
import java.sql.Timestamp;
import java.util.Map;
import java.math.BigDecimal;
import java.util.regex.Pattern;


public class UrlRepository extends BaseRepository {

    // Конструктор, который устанавливает соединение с базой данных
    public UrlRepository(Connection connection) {
        super(connection);
    }

    public void initializeDatabase() {
        try (Statement statement = connection.createStatement()) {
            String createUrlsTableSql = "CREATE TABLE IF NOT EXISTS urls (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "name VARCHAR(255) NOT NULL," +
                    "created_at TIMESTAMP NOT NULL" +
                    ")";
            statement.executeUpdate(createUrlsTableSql);

            String createChecksTableSql = "CREATE TABLE IF NOT EXISTS Checks (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "url_id BIGINT," +
                    "title VARCHAR(255)," +
                    "h1 VARCHAR(255)," +
                    "description TEXT," +
                    "created_at TIMESTAMP NOT NULL," +
                    "FOREIGN KEY (url_id) REFERENCES urls(id)" +
                    ")";
            statement.executeUpdate(createChecksTableSql);

            String createTFIDFResultsTableSql = "CREATE TABLE IF NOT EXISTS TFIDFResults (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "url_id BIGINT," +
                    "word VARCHAR(255)," +
                    "tfidf DOUBLE PRECISION," +
                    "created_at TIMESTAMP NOT NULL," +
                    "FOREIGN KEY (url_id) REFERENCES urls(id)" +
                    ")";
            statement.executeUpdate(createTFIDFResultsTableSql);

            String createSpeedAnalysisTableSql = "CREATE TABLE IF NOT EXISTS SpeedAnalysis (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "url_id BIGINT," +
                    "load_time BIGINT NOT NULL," +
                    "content_length INT NOT NULL," +
                    "request_count INT NOT NULL," +
                    "is_cdn_used BOOLEAN NOT NULL," +
                    "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
                    "FOREIGN KEY (url_id) REFERENCES urls(id)" +
                    ")";
            statement.executeUpdate(createSpeedAnalysisTableSql);

            String createLinkTableSql = "CREATE TABLE IF NOT EXISTS Links (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "url_id BIGINT," +
                    "url VARCHAR(255) NOT NULL," +
                    "statusCode INTEGER NOT NULL," +
                    "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
                    "FOREIGN KEY (url_id) REFERENCES urls(id)" +
                    ")";
            statement.executeUpdate(createLinkTableSql);

            System.out.println("Tables 'urls', 'Checks','TFIDFResults', 'SpeedAnalysis' and 'Links' created successfully");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    // Метод для проверки существования URL в базе данных
    public boolean exists(String url) {
        String sql = "SELECT COUNT(*) FROM urls WHERE name = ?";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, url);
            try (ResultSet resultSet = statement.executeQuery()) {
                resultSet.next();
                return resultSet.getInt(1) > 0;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    // Метод для добавления URL в базу данных
    public void addUrl(String url) {
        String sql = "INSERT INTO urls (name, created_at) VALUES (?, NOW())";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, url);
            statement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public Url getLastInsertedUrl() {
        Url url = null;
        String sql = "SELECT * FROM urls ORDER BY id DESC LIMIT 1";
        try (PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {
            if (resultSet.next()) {
                url = new Url();
                url.setId(resultSet.getLong("id"));
                url.setName(resultSet.getString("name"));
                Timestamp timestamp = resultSet.getTimestamp("created_at");
                LocalDateTime createdAt = timestamp.toLocalDateTime();
                url.setCreatedAt(createdAt);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return url;
    }

    public List<Url> getAllUrls() {
        List<Url> urls = new ArrayList<>();
        String sql = "SELECT * FROM urls"; // Получаем все данные из таблицы urls
        try (PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                Url url = new Url();
                url.setId(resultSet.getLong("id"));
                url.setName(resultSet.getString("name"));

                // Получаем дату и время в формате Timestamp
                Timestamp timestamp = resultSet.getTimestamp("created_at");
                // Преобразуем Timestamp в LocalDateTime
                LocalDateTime createdAt = timestamp.toLocalDateTime();

                url.setCreatedAt(createdAt);
                urls.add(url);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return urls;
    }

    // Метод для получения URL по идентификатору из базы данных
    public Url getUrlById(long id) {
        Url url = null;
        String sql = "SELECT id, name, created_at FROM urls WHERE id = ?";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setLong(1, id);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    long urlId = resultSet.getLong("id");
                    String name = resultSet.getString("name");
                    LocalDateTime createdAt = resultSet.getTimestamp("created_at").toLocalDateTime();
                    url = new Url(urlId, name, createdAt); // Используем конструктор с параметрами
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return url;
    }

    public void deleteSpeedAnalysisById(List<Long> ids) {
        String sql = "DELETE FROM SpeedAnalysis WHERE url_id = ?";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            for (Long id : ids) {
                statement.setLong(1, id);
                statement.executeUpdate();
            }
            System.out.println("Speed analysis data deleted successfully for ids: " + ids);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public Long getUrlIdByName(String name) {
        Long urlId = null;
        String sql = "SELECT id FROM urls WHERE name = ?";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, name);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    urlId = resultSet.getLong("id");
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return urlId;
    }

    public void addUrlCheck(String url, String title, String h1, String description) {
        try {
            Long urlId = getUrlIdByName(url); // Получаем id URL
            if (urlId != null) {
                PreparedStatement statement = connection.prepareStatement("INSERT INTO Checks (url_id, title, h1, description, created_at) VALUES (?, ?, ?, ?, ?)");
                statement.setLong(1, urlId);
                statement.setString(2, title);
                statement.setString(3, h1);
                statement.setString(4, description);
                statement.setTimestamp(5, java.sql.Timestamp.valueOf(LocalDateTime.now()));
                statement.executeUpdate();
            } else {
                System.out.println("URL not found: " + url);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public List<UrlCheck> getAllUrlChecks() {
        List<UrlCheck> urlChecks = new ArrayList<>();
        String sql = "SELECT * FROM Checks";
        try (PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                UrlCheck urlCheck = new UrlCheck();
                urlCheck.setId(resultSet.getLong("id"));
                urlCheck.setUrl(resultSet.getLong("url_id"));
                urlCheck.setTitle(resultSet.getString("title"));
                urlCheck.setH1(resultSet.getString("h1"));
                urlCheck.setDescription(resultSet.getString("description"));
                Timestamp timestamp = resultSet.getTimestamp("created_at");

                LocalDateTime createdAt = timestamp.toLocalDateTime();
                urlCheck.setCreatedAt(createdAt);

                urlChecks.add(urlCheck);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return urlChecks;
    }

    public void addTFIDFCheck(String url, Map<String, Double> tfidfMap) {
        try {
            Long urlId = getUrlIdByName(url);
            if (urlId != null) {
                PreparedStatement statement = connection.prepareStatement("INSERT INTO TFIDFResults (url_id, word, tfidf, created_at) VALUES (?, ?, ?, ?)");
                for (Map.Entry<String, Double> entry : tfidfMap.entrySet()) {
                    String word = entry.getKey();
                    Double tfidf = entry.getValue();

                    BigDecimal tfidfBigDecimal = BigDecimal.valueOf(tfidf);

                    statement.setLong(1, urlId);
                    statement.setString(2, word);
                    statement.setBigDecimal(3, tfidfBigDecimal);
                    statement.setTimestamp(4, Timestamp.valueOf(LocalDateTime.now()));
                    statement.executeUpdate();
                }
            } else {
                System.out.println("URL not found: " + url);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public List<TFIDFCheck> getAllTFIDFChecks() {
        List<TFIDFCheck> tfidfchecks = new ArrayList<>();
        String sql = "SELECT id, url_id, word, created_at FROM TFIDFResults";
        try (PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                TFIDFCheck tfidfcheck = new TFIDFCheck();
                tfidfcheck.setId(resultSet.getLong("id"));
                tfidfcheck.setUrlId(resultSet.getLong("url_id"));
                tfidfcheck.setWord(resultSet.getString("word"));

                Timestamp timestamp = resultSet.getTimestamp("created_at");
                // Преобразуем Timestamp в LocalDateTime
                LocalDateTime createdAt = timestamp.toLocalDateTime();
                tfidfcheck.setCreatedAt(createdAt);

                tfidfchecks.add(tfidfcheck);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return tfidfchecks;
    }

    public void addPageAnalysis(String url, Long loadTime, Integer contentLength, Integer requestCount, Boolean isCdnUsed) {
        try {
            Long urlId = getUrlIdByName(url);
            if (urlId != null) {
                PreparedStatement statement = connection.prepareStatement("INSERT INTO SpeedAnalysis (url_id, load_time, content_length, request_count, is_cdn_used, created_at) VALUES (?, ?, ?, ?, ?, ?)");
                statement.setLong(1, urlId);
                statement.setLong(2, loadTime);
                statement.setInt(3, contentLength);
                statement.setInt(4, requestCount);
                statement.setBoolean(5, isCdnUsed);
                statement.setTimestamp(6, Timestamp.valueOf(LocalDateTime.now()));
                statement.executeUpdate();
            } else {
                System.out.println("URL not found: " + url);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public List<PageSpeedAnalysis> getAllSpeedAnalysis() {
        List<PageSpeedAnalysis> pagespeedAnalysisList = new ArrayList<>();
        String sql = "SELECT id, url_id, load_time, content_length, created_at FROM SpeedAnalysis";
        try (PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                PageSpeedAnalysis pagespeedAnalysis = new PageSpeedAnalysis();
                pagespeedAnalysis.setId(resultSet.getLong("id"));
                pagespeedAnalysis.setUrlId(resultSet.getLong("url_id"));
                pagespeedAnalysis.setLoadTime(resultSet.getLong("load_time"));
                pagespeedAnalysis.setContentLength(resultSet.getInt("content_length"));

                Timestamp timestamp = resultSet.getTimestamp("created_at");
                // Преобразуем Timestamp в LocalDateTime
                LocalDateTime createdAt = timestamp.toLocalDateTime();
                pagespeedAnalysis.setCreatedAt(createdAt);

                pagespeedAnalysisList.add(pagespeedAnalysis);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return pagespeedAnalysisList;
    }

    public List<Long> getAllLoadTimes() {
        List<Long> loadTimeList = new ArrayList<>();
        String sql = "SELECT load_time FROM SpeedAnalysis";
        try (PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                Long loadTime = resultSet.getLong("load_time");
                loadTimeList.add(loadTime);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return loadTimeList;
    }

    public List<String> getAllLoadTitle() {
        List<String> loadTitleList = new ArrayList<>();
        String sql = "SELECT title FROM Checks";
        try (PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                String loadTitle = resultSet.getString("title");
                loadTitleList.add(loadTitle);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return loadTitleList;
    }

    public List<String> getAllLoadDescription() {
        List<String> loadDescriptionList = new ArrayList<>();
        String sql = "SELECT description FROM Checks";
        try (PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                String loadDescription = resultSet.getString("description");
                loadDescriptionList.add(loadDescription);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return loadDescriptionList;
    }

    public ValidationResult validateTitle(String title) {
        if (title.length() < 30) {
            return new ValidationResult(false, "Заголовок слишком короткий. Минимальная длина 30 символов.");
        }
        if (title.length() > 60) {
            return new ValidationResult(false, "Заголовок слишком длинный. Максимальная длина 60 символов.");
        }
        if (!Pattern.matches("^[a-zA-Z0-9\\s]+$", title)) {
            String invalidChars = title.replaceAll("[a-zA-Z0-9\\s]", "");
            return new ValidationResult(false, "Заголовок содержит недопустимые символы: " + invalidChars);
        }
        return new ValidationResult(true, "Заголовок корректный.");
    }

    public ValidationResult validateDescription(String description) {
        if (description.length() < 70) {
            return new ValidationResult(false, "Описание слишком короткое. Минимальная длина 70 символов.");
        }
        if (description.length() > 160) {
            return new ValidationResult(false, "Описание слишком длинное. Максимальная длина 160 символов.");
        }
        if (!Pattern.matches("^[a-zA-Z0-9\\s]+$", description)) {
            String invalidChars = description.replaceAll("[a-zA-Z0-9\\s]", "");
            return new ValidationResult(false, "Описание содержит недопустимые символы: " + invalidChars);
        }
        return new ValidationResult(true, "Описание корректное.");
    }

    public List<Integer> getAllContentLengths() {
        List<Integer> contentLengthList = new ArrayList<>();
        String sql = "SELECT content_length FROM SpeedAnalysis";
        try (PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                Integer contentLength = resultSet.getInt("content_length");
                contentLengthList.add(contentLength);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return contentLengthList;
    }

    public void saveUrlStatus(String url, int statusCode) throws SQLException {
        Long urlId = getUrlIdByName(url);
        if (urlId != null) {
            try {
                PreparedStatement statement = connection.prepareStatement("INSERT INTO Links (url_id, url, statusCode, created_at) VALUES (?, ?, ?, ?)");
                statement.setLong(1, urlId);
                statement.setString(2, url);
                statement.setInt(3, statusCode);
                statement.setTimestamp(4, Timestamp.valueOf(LocalDateTime.now()));
                statement.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
                throw new SQLException("Error occurred while saving URL status to the database: " + e.getMessage());
            }
        } else {
            throw new SQLException("URL not found: " + url);
        }
    }

    public List<LinkCheck> getAllLinkChecks() {
        List<LinkCheck> linkChecks = new ArrayList<>();
        String sql = "SELECT id, url_id, url, statusCode, created_at FROM Links";
        try (PreparedStatement statement = connection.prepareStatement(sql);
             ResultSet resultSet = statement.executeQuery()) {
            while (resultSet.next()) {
                LinkCheck linkCheck = new LinkCheck();
                linkCheck.setId(resultSet.getLong("id"));
                linkCheck.setUrlId(resultSet.getLong("url_id"));
                linkCheck.setUrl(resultSet.getString("url"));
                linkCheck.setStatusCode(resultSet.getInt("statusCode"));

                Timestamp timestamp = resultSet.getTimestamp("created_at");
                LocalDateTime checkedAt = timestamp.toLocalDateTime();
                linkCheck.setCheckedAt(checkedAt);

                linkChecks.add(linkCheck);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return linkChecks;
    }
}
